# Generated by Django 6.0 on 2025-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
